name: syntax
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0-409.0.dev

# Add regular dependencies here.
dependencies:
  collection: ^1.17.2
  fast_immutable_collections: ^9.1.1
  freezed_annotation: ^2.2.0
  meta: ^1.9.1
  path: ^1.8.3
  petitparser: ^5.4.0

dev_dependencies:
  build_runner: ^2.4.4
  freezed: ^2.3.4
  lints: ^2.1.0
  test: ^1.24.3
