name: syntax
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  collection: ^1.17.2
  fast_immutable_collections: ^10.2.2
  freezed_annotation: ^2.2.0
  meta: ^1.9.1
  path: ^1.8.3
  petitparser: ^6.0.2
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
  freezed: ^2.3.4
  lints: ^3.0.0
  test: ^1.24.3
